-- ==============================================================================
-- MATCHPET - BANCO DE DADOS COMPLETO E DEFINITIVO (SUPABASE POSTGRESQL)
-- ==============================================================================

-- 1. LIMPEZA SEGURA DE TABELAS ANTERIORES (GARANTE EXECUÇÃO 100% LIMPA)
DROP TABLE IF EXISTS public.solicitations CASCADE;
DROP TABLE IF EXISTS public.foster_requests CASCADE;
DROP TABLE IF EXISTS public.pets CASCADE;
DROP TABLE IF EXISTS public.ongs CASCADE;
DROP TABLE IF EXISTS public.usuarios CASCADE;

-- 2. TABELA DE ONGS CREDENCIADAS
CREATE TABLE public.ongs (
    id TEXT PRIMARY KEY,
    cnpj VARCHAR(20) UNIQUE NOT NULL,
    name TEXT NOT NULL,
    city TEXT NOT NULL,
    state VARCHAR(2) NOT NULL,
    phone TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    senha_hash TEXT NOT NULL,
    address TEXT NOT NULL,
    image TEXT,
    description TEXT,
    pets_count INTEGER DEFAULT 0,
    featured BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABELA DE USUÁRIOS (ADOTANTES E ADMIN)
CREATE TABLE public.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    senha_hash TEXT NOT NULL,
    role TEXT DEFAULT 'user' NOT NULL, -- 'user' (adotante) ou 'admin'
    telefone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABELA DE PETS (ISOLAMENTO E VINCULAÇÃO POR ONG_ID)
CREATE TABLE public.pets (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    species TEXT DEFAULT 'Cachorro' NOT NULL,
    breed TEXT,
    city TEXT NOT NULL,
    state VARCHAR(2) NOT NULL,
    age TEXT NOT NULL,
    age_group TEXT DEFAULT 'Adulto',
    gender TEXT NOT NULL,
    size TEXT NOT NULL,
    color TEXT,
    vaccination TEXT DEFAULT 'Vacinado',
    castrated BOOLEAN DEFAULT true,
    dewormed BOOLEAN DEFAULT true,
    special_needs BOOLEAN DEFAULT false,
    main_image TEXT NOT NULL,
    gallery_images TEXT[] DEFAULT '{}',
    ong_id TEXT NOT NULL,
    ong_name TEXT NOT NULL,
    entry_date TEXT,
    status TEXT DEFAULT 'Disponível',
    favorite BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. TABELA DE SOLICITAÇÕES DE ADOÇÃO E VISITAS (ISOLAMENTO POR ONG_ID)
CREATE TABLE public.solicitations (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL, -- 'Visita' ou 'Adoção'
    pet_id TEXT NOT NULL,
    pet_name TEXT NOT NULL,
    pet_image TEXT,
    requester_name TEXT NOT NULL,
    requester_email TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    date_or_details TEXT NOT NULL,
    status TEXT DEFAULT 'pending' NOT NULL, -- 'pending', 'in_review', 'approved', 'rejected'
    adoption_granted BOOLEAN DEFAULT false,
    ong_id TEXT NOT NULL,
    ong_name TEXT NOT NULL,
    ong_phone TEXT,
    ong_email TEXT,
    ong_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. TABELA DE PEDIDOS DE ACOLHIMENTO E TRIAGEM
CREATE TABLE public.foster_requests (
    id TEXT PRIMARY KEY,
    pet_name TEXT NOT NULL,
    species TEXT NOT NULL,
    size TEXT,
    reason TEXT NOT NULL,
    timestamp TEXT,
    status TEXT DEFAULT 'pending' NOT NULL, -- 'pending', 'accepted', 'declined'
    photo_url TEXT,
    requester_name TEXT,
    requester_email TEXT,
    phone TEXT,
    accepted_by_ong_id TEXT,
    accepted_by_ong_name TEXT,
    accepted_by_ong_phone TEXT,
    accepted_by_ong_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. ÍNDICES DE PERFORMANCE E ISOLAMENTO DE DADOS
CREATE INDEX idx_pets_ong_id ON public.pets(ong_id);
CREATE INDEX idx_solicitations_ong_id ON public.solicitations(ong_id);
CREATE INDEX idx_solicitations_requester ON public.solicitations(requester_email);
CREATE INDEX idx_foster_accepted_ong ON public.foster_requests(accepted_by_ong_id);
CREATE INDEX idx_ongs_cnpj ON public.ongs(cnpj);
CREATE INDEX idx_ongs_email ON public.ongs(email);

-- 8. POLÍTICAS DE ROW LEVEL SECURITY (RLS)
ALTER TABLE public.ongs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.solicitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.foster_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public access on ongs" ON public.ongs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access on pets" ON public.pets FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access on solicitations" ON public.solicitations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access on foster_requests" ON public.foster_requests FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Public access on usuarios" ON public.usuarios FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- SEED INICIAL: DADOS COMPLETOS PARA O MATCHPET FUNCIONAR IMEDIATAMENTE
-- ==============================================================================

-- A. CONTA DO ADMINISTRADOR GERAL
-- Email: admin@gmail.com | Senha: hiqufxAqTYouTeJmYqFYPHFELoUEXwtc
INSERT INTO public.usuarios (nome, email, senha_hash, role, telefone)
VALUES (
    'Administrador MatchPet',
    'admin@gmail.com',
    '014a09a56a6ecfa1beff5e8eb5047bca8fd1f26e2e50529d4791338d4a9ccbfe',
    'admin',
    '(11) 99999-9999'
);

-- B. ONGS PARCEIRAS INICIAIS
-- Todas têm senha padrão: admin123 (Hash SHA-256: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918)
INSERT INTO public.ongs (id, cnpj, name, city, state, phone, email, senha_hash, address, image, description, pets_count, featured)
VALUES
(
    'ong-amigos-de-patas',
    '12.345.678/0001-90',
    'Amigos de Patas',
    'São Paulo',
    'SP',
    '(11) 98765-4321',
    'contato@amigosdepatas.org.br',
    '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918',
    'Av. Paulista, 1200 - Bela Vista, São Paulo - SP',
    'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=800&q=80',
    'Instalações acolhedoras dedicadas ao resgate, reabilitação e adoção responsável de cães e gatos.',
    48,
    true
),
(
    'ong-refugio-animal',
    '98.765.432/0001-10',
    'Refúgio Animal',
    'Campinas',
    'SP',
    '(19) 99887-6655',
    'adocao@refugioanimal.org.br',
    '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918',
    'Rua das Flores, 450 - Taquaral, Campinas - SP',
    'https://images.unsplash.com/photo-1535268647677-300dbf3d78d1?auto=format&fit=crop&w=800&q=80',
    'Comunidade engajada com equipe veterinária focada em acolhimento e filhotes resgatados.',
    35,
    true
),
(
    'ong-sos-focinhos',
    '45.678.901/0001-23',
    'SOS Focinhos',
    'Rio de Janeiro',
    'RJ',
    '(21) 97766-5544',
    'focinhos@sosfocinhos.org.br',
    '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918',
    'Rua Barata Ribeiro, 300 - Copacabana, Rio de Janeiro - RJ',
    'https://images.unsplash.com/photo-1596492784531-6e6eb5ea9993?auto=format&fit=crop&w=800&q=80',
    'Resgate urbano e programas de socialização e feiras de adoção semanais.',
    59,
    true
),
(
    'ong-instituto-patinhas',
    '78.901.234/0001-56',
    'Instituto Patinhas de Ouro',
    'São Paulo',
    'SP',
    '(11) 97123-9988',
    'adotar@patinhasdeouro.org.br',
    '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918',
    'Rua Vergueiro, 2500 - Vila Mariana, São Paulo - SP',
    'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=800&q=80',
    'Especializada no resgate e recuperação de cães de todos os portes com recreação.',
    22,
    false
);

-- C. PETS INICIAIS (COM ISOLAMENTO POR ONG)
INSERT INTO public.pets (id, name, species, breed, city, state, age, age_group, gender, size, color, vaccination, castrated, dewormed, main_image, gallery_images, ong_id, ong_name, entry_date, status, favorite)
VALUES
(
    'thor',
    'Thor',
    'Cachorro',
    'Mestiço de Golden Retriever',
    'São Paulo',
    'SP',
    '2 Anos',
    'Adulto',
    'Macho',
    'Grande',
    'Dourado e Branco',
    'Vacinado',
    true,
    true,
    'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=800&q=80',
    ARRAY['https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&q=80'],
    'ong-instituto-patinhas',
    'Instituto Patinhas de Ouro',
    '15/08/2023',
    'Disponível',
    false
),
(
    'caramelo',
    'Caramelo',
    'Cachorro',
    'Vira-lata (SRD)',
    'São Paulo',
    'SP',
    '2 anos',
    'Adulto',
    'Macho',
    'Médio',
    'Caramelo',
    'Vacinado',
    true,
    true,
    'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=800&q=80',
    ARRAY[]::TEXT[],
    'ong-amigos-de-patas',
    'Amigos de Patas',
    '20/09/2023',
    'Disponível',
    false
),
(
    'luna',
    'Luna',
    'Gato',
    'Persa Mestiço',
    'Campinas',
    'SP',
    '1 ano',
    'Adulto',
    'Fêmea',
    'Pequeno',
    'Branco',
    'Vacinado',
    true,
    true,
    'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=800&q=80',
    ARRAY[]::TEXT[],
    'ong-refugio-animal',
    'Refúgio Animal',
    '05/09/2023',
    'Em Processo',
    false
),
(
    'bolinha',
    'Bolinha',
    'Cachorro',
    'Border Collie Mix',
    'Rio de Janeiro',
    'RJ',
    '3 meses',
    'Filhote',
    'Macho',
    'Pequeno',
    'Preto e Branco',
    'Vacinado',
    false,
    true,
    'https://images.unsplash.com/photo-1546527868-ccb7ee7dfa6a?auto=format&fit=crop&w=800&q=80',
    ARRAY[]::TEXT[],
    'ong-sos-focinhos',
    'SOS Focinhos',
    '12/10/2023',
    'Disponível',
    false
),
(
    'rex',
    'Rex',
    'Cachorro',
    'Golden Retriever Idoso',
    'Rio de Janeiro',
    'RJ',
    '8 anos',
    'Idoso',
    'Macho',
    'Grande',
    'Dourado',
    'Vacinado',
    true,
    true,
    'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=800&q=80',
    ARRAY[]::TEXT[],
    'ong-sos-focinhos',
    'SOS Focinhos',
    '01/07/2023',
    'Disponível',
    false
);

-- D. SOLICITAÇÕES INICIAIS
INSERT INTO public.solicitations (id, type, pet_id, pet_name, pet_image, requester_name, requester_email, date_or_details, status, phone, email, ong_id, ong_name, ong_phone, ong_email, ong_address, adoption_granted)
VALUES
(
    'sol-1',
    'Visita',
    'bolinha',
    'Bolinha',
    'https://images.unsplash.com/photo-1546527868-ccb7ee7dfa6a?auto=format&fit=crop&w=800&q=80',
    'Adotante',
    'user@gmail.com',
    'Sábado, 14h às 16h',
    'in_review',
    '(11) 98112-3344',
    'user@gmail.com',
    'ong-sos-focinhos',
    'SOS Focinhos',
    '(21) 97766-5544',
    'focinhos@sosfocinhos.org.br',
    'Rua Barata Ribeiro, 300 - Rio de Janeiro - RJ',
    false
),
(
    'sol-2',
    'Adoção',
    'thor',
    'Thor',
    'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=800&q=80',
    'Adotante',
    'user@gmail.com',
    'Formulário completo preenchido (Casa com quintal telado)',
    'approved',
    '(11) 98112-3344',
    'user@gmail.com',
    'ong-instituto-patinhas',
    'Instituto Patinhas de Ouro',
    '(11) 97123-9988',
    'adotar@patinhasdeouro.org.br',
    'Rua Vergueiro, 2500 - Vila Mariana, São Paulo - SP',
    true
);

-- E. PEDIDOS DE ACOLHIMENTO E TRIAGEM INICIAIS
INSERT INTO public.foster_requests (id, pet_name, species, size, reason, timestamp, status, photo_url, requester_name, requester_email, phone, accepted_by_ong_id, accepted_by_ong_name, accepted_by_ong_phone, accepted_by_ong_address)
VALUES
(
    'foster-1',
    'Max',
    'Cachorro',
    'Grande',
    'Triagem iniciada: Impossibilidade de acolhimento definitivo por diagnóstico de alergia crônica.',
    'Ontem, 16:45',
    'accepted',
    'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=600&q=80',
    'Adotante',
    'user@gmail.com',
    '(11) 97722-1199',
    'ong-amigos-de-patas',
    'Amigos de Patas',
    '(11) 98765-4321',
    'Av. Paulista, 1200 - Bela Vista, São Paulo - SP'
);
