-- ==============================================================================
-- SCHEMA MATCHPET - SISTEMA DE ADOÇÃO COM AUTENTICAÇÃO MULTI-PERFIL E ISOLAMENTO
-- SCRIPT TOTALMENTE IDEMPOTENTE E RESILIENTE A TABELAS PRÉ-EXISTENTES
-- ==============================================================================

-- 1. TABELA DE ONGS CREDENCIADAS
CREATE TABLE IF NOT EXISTS public.ongs (
    id TEXT PRIMARY KEY,
    cnpj VARCHAR(20),
    name TEXT NOT NULL,
    city TEXT NOT NULL,
    state VARCHAR(2) NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    senha_hash TEXT,
    address TEXT,
    image TEXT,
    description TEXT,
    pets_count INTEGER DEFAULT 0,
    featured BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Garantir que todas as colunas de ONGs existam caso a tabela já tenha sido criada anteriormente
ALTER TABLE public.ongs ADD COLUMN IF NOT EXISTS cnpj VARCHAR(20);
ALTER TABLE public.ongs ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE public.ongs ADD COLUMN IF NOT EXISTS senha_hash TEXT;
ALTER TABLE public.ongs ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE public.ongs ADD COLUMN IF NOT EXISTS pets_count INTEGER DEFAULT 0;
ALTER TABLE public.ongs ADD COLUMN IF NOT EXISTS featured BOOLEAN DEFAULT false;


-- 2. TABELA DE USUÁRIOS (ADOTANTES E ADMIN)
CREATE TABLE IF NOT EXISTS public.usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    senha_hash TEXT NOT NULL,
    role TEXT DEFAULT 'user' NOT NULL, -- 'user' ou 'admin'
    telefone TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user';
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS telefone TEXT;


-- 3. TABELA DE PETS (VINCULADOS AUTOMATICAMENTE POR ONG_ID)
CREATE TABLE IF NOT EXISTS public.pets (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    species TEXT DEFAULT 'Cachorro' NOT NULL,
    breed TEXT,
    city TEXT NOT NULL,
    state VARCHAR(2) NOT NULL,
    age TEXT NOT NULL,
    age_group TEXT DEFAULT 'Adulto',
    gender TEXT NOT NULL,
    size TEXT NOT NULL,
    color TEXT,
    vaccination TEXT DEFAULT 'Vacinado',
    castrated BOOLEAN DEFAULT true,
    dewormed BOOLEAN DEFAULT true,
    special_needs BOOLEAN DEFAULT false,
    main_image TEXT NOT NULL,
    gallery_images TEXT[] DEFAULT '{}',
    ong_id TEXT,
    ong_name TEXT,
    entry_date TEXT,
    status TEXT DEFAULT 'Disponível',
    favorite BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Garantir colunas de isolamento e metadados na tabela pets
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS ong_id TEXT DEFAULT 'ong-amigos-de-patas';
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS ong_name TEXT DEFAULT 'Amigos de Patas';
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS species TEXT DEFAULT 'Cachorro';
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS breed TEXT;
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS city TEXT DEFAULT 'São Paulo';
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS state VARCHAR(2) DEFAULT 'SP';
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS age TEXT DEFAULT '2 anos';
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS age_group TEXT DEFAULT 'Adulto';
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS gender TEXT DEFAULT 'Macho';
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS size TEXT DEFAULT 'Médio';
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS color TEXT;
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS vaccination TEXT DEFAULT 'Vacinado';
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS castrated BOOLEAN DEFAULT true;
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS dewormed BOOLEAN DEFAULT true;
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS special_needs BOOLEAN DEFAULT false;
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS main_image TEXT;
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS gallery_images TEXT[] DEFAULT '{}';
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'Disponível';
ALTER TABLE public.pets ADD COLUMN IF NOT EXISTS favorite BOOLEAN DEFAULT false;


-- 4. TABELA DE SOLICITAÇÕES DE ADOÇÃO E VISITAS (ISOLAMENTO POR ONG_ID)
CREATE TABLE IF NOT EXISTS public.solicitations (
    id TEXT PRIMARY KEY,
    type TEXT NOT NULL, -- 'Visita' ou 'Adoção'
    pet_id TEXT NOT NULL,
    pet_name TEXT NOT NULL,
    pet_image TEXT,
    requester_name TEXT NOT NULL,
    requester_email TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    date_or_details TEXT NOT NULL,
    status TEXT DEFAULT 'pending' NOT NULL, -- 'pending', 'in_review', 'approved', 'rejected'
    adoption_granted BOOLEAN DEFAULT false,
    ong_id TEXT,
    ong_name TEXT,
    ong_phone TEXT,
    ong_email TEXT,
    ong_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Garantir colunas de isolamento e contato de ONGs na tabela solicitations
ALTER TABLE public.solicitations ADD COLUMN IF NOT EXISTS ong_id TEXT;
ALTER TABLE public.solicitations ADD COLUMN IF NOT EXISTS ong_name TEXT;
ALTER TABLE public.solicitations ADD COLUMN IF NOT EXISTS ong_phone TEXT;
ALTER TABLE public.solicitations ADD COLUMN IF NOT EXISTS ong_email TEXT;
ALTER TABLE public.solicitations ADD COLUMN IF NOT EXISTS ong_address TEXT;
ALTER TABLE public.solicitations ADD COLUMN IF NOT EXISTS adoption_granted BOOLEAN DEFAULT false;
ALTER TABLE public.solicitations ADD COLUMN IF NOT EXISTS pet_image TEXT;
ALTER TABLE public.solicitations ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE public.solicitations ADD COLUMN IF NOT EXISTS email TEXT;


-- 5. TABELA DE PEDIDOS DE ACOLHIMENTO E TRIAGEM
CREATE TABLE IF NOT EXISTS public.foster_requests (
    id TEXT PRIMARY KEY,
    pet_name TEXT NOT NULL,
    species TEXT NOT NULL,
    size TEXT,
    reason TEXT NOT NULL,
    timestamp TEXT,
    status TEXT DEFAULT 'pending' NOT NULL, -- 'pending', 'accepted', 'declined'
    photo_url TEXT,
    requester_name TEXT,
    requester_email TEXT,
    phone TEXT,
    accepted_by_ong_id TEXT,
    accepted_by_ong_name TEXT,
    accepted_by_ong_phone TEXT,
    accepted_by_ong_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Garantir colunas de aceite e ONG acolhedora na tabela foster_requests
ALTER TABLE public.foster_requests ADD COLUMN IF NOT EXISTS accepted_by_ong_id TEXT;
ALTER TABLE public.foster_requests ADD COLUMN IF NOT EXISTS accepted_by_ong_name TEXT;
ALTER TABLE public.foster_requests ADD COLUMN IF NOT EXISTS accepted_by_ong_phone TEXT;
ALTER TABLE public.foster_requests ADD COLUMN IF NOT EXISTS accepted_by_ong_address TEXT;
ALTER TABLE public.foster_requests ADD COLUMN IF NOT EXISTS requester_name TEXT;
ALTER TABLE public.foster_requests ADD COLUMN IF NOT EXISTS requester_email TEXT;
ALTER TABLE public.foster_requests ADD COLUMN IF NOT EXISTS photo_url TEXT;


-- 6. ÍNDICES DE PERFORMANCE E ISOLAMENTO
CREATE INDEX IF NOT EXISTS idx_pets_ong_id ON public.pets(ong_id);
CREATE INDEX IF NOT EXISTS idx_solicitations_ong_id ON public.solicitations(ong_id);
CREATE INDEX IF NOT EXISTS idx_solicitations_requester ON public.solicitations(requester_email);
CREATE INDEX IF NOT EXISTS idx_foster_accepted_ong ON public.foster_requests(accepted_by_ong_id);
CREATE INDEX IF NOT EXISTS idx_ongs_cnpj ON public.ongs(cnpj);
CREATE INDEX IF NOT EXISTS idx_ongs_email ON public.ongs(email);


-- 7. SEED INICIAL: CONTA DE ADMINISTRADOR
-- Senha do admin: hiqufxAqTYouTeJmYqFYPHFELoUEXwtc (Hash SHA-256: 014a09a56a6ecfa1beff5e8eb5047bca8fd1f26e2e50529d4791338d4a9ccbfe)
INSERT INTO public.usuarios (nome, email, senha_hash, role)
VALUES (
    'Administrador MatchPet',
    'admin@gmail.com',
    '014a09a56a6ecfa1beff5e8eb5047bca8fd1f26e2e50529d4791338d4a9ccbfe',
    'admin'
)
ON CONFLICT (email) DO UPDATE 
SET senha_hash = EXCLUDED.senha_hash, role = 'admin';


-- 8. POLÍTICAS DE ROW LEVEL SECURITY (RLS)
ALTER TABLE public.ongs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.solicitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.foster_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;

-- Permissões públicas para leitura / operações do aplicativo
DO $$ BEGIN
    DROP POLICY IF EXISTS "Public access on ongs" ON public.ongs;
    CREATE POLICY "Public access on ongs" ON public.ongs FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Public access on pets" ON public.pets;
    CREATE POLICY "Public access on pets" ON public.pets FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Public access on solicitations" ON public.solicitations;
    CREATE POLICY "Public access on solicitations" ON public.solicitations FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Public access on foster_requests" ON public.foster_requests;
    CREATE POLICY "Public access on foster_requests" ON public.foster_requests FOR ALL USING (true) WITH CHECK (true);

    DROP POLICY IF EXISTS "Public access on usuarios" ON public.usuarios;
    CREATE POLICY "Public access on usuarios" ON public.usuarios FOR ALL USING (true) WITH CHECK (true);
END $$;
